_BASE_: "multitasklunet.yaml"
DEBUG: True

TRAINER:
  BATCH_SIZE: 2

MODEL:
  CONS_LOSS_TYPE: 'ConsLoss'

DATALOADER:
  TIMESERIES_LENGTH: 5

AUGMENTATION:
  CROP_SIZE: 64
  IMAGE_OVERSAMPLING_TYPE: 'none'