_BASE_: "base.yaml"

MODEL:
  TYPE: 'unetformermultitask'
  TRANSFORMER: True
  TRANSFORMER_PARAMS:
    N_HEADS: 2
  MAP_FROM_CHANGES: True

DATALOADER:
  INCLUDE_CHANGE_LABEL: True

AUGMENTATION:
  CROP_SIZE: 128