_BASE_: "base.yaml"

MODEL:
  TYPE: 'unetouttransformerv5'
  TRANSFORMER: True
  TRANSFORMER_PARAMS:
    N_HEADS: 2
    SPATIAL_ATTENTION_SIZE: 3
  MAP_FROM_CHANGES: True
  ADJACENT_CHANGES: False

DATALOADER:
  INCLUDE_CHANGE_LABEL: True

AUGMENTATION:
  CROP_SIZE: 128