_BASE_: "base.yaml"

MODEL:
  TYPE: 'unetouttransformermultitask'
  TRANSFORMER: True
  TRANSFORMER_PARAMS:
    N_HEADS: 2
  MAP_FROM_CHANGES: True
  ADJACENT_CHANGES: False

DATALOADER:
  INCLUDE_CHANGE_LABEL: True