_BASE_: "base.yaml"

MODEL:
  TYPE: 'unetouttransformerv4'
  TRANSFORMER: True
  TRANSFORMER_PARAMS:
    N_HEADS: 2
  MAP_FROM_CHANGES: True
  ADJACENT_CHANGES: False

DATALOADER:
  INCLUDE_CHANGE_LABEL: True

AUGMENTATION:
  IMAGE_OVERSAMPLING_TYPE: 'change'